CREATE TABLE IF NOT EXISTS `reminders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `friend_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` TINYINT(5) NOT NULL DEFAULT 10,
  PRIMARY KEY (id),
  FOREIGN KEY (friend_id) REFERENCES friends(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
